# Generated by Django 5.1.5 on 2026-08-26 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BespokeInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inquiry_id', models.CharField(blank=True, max_length=30, unique=True)),
                ('client_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('piece_type', models.CharField(max_length=100)),
                ('gemstone', models.CharField(max_length=100)),
                ('metal', models.CharField(max_length=100)),
                ('carat_weight', models.DecimalField(decimal_places=2, default=2.0, max_digits=5)),
                ('setting_style', models.CharField(max_length=100)),
                ('estimated_price_inr', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('custom_engraving', models.CharField(blank=True, max_length=150)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Bespoke Inquiry',
                'verbose_name_plural': 'Bespoke Inquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('tagline', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('hero_image', models.URLField(blank=True, max_length=500)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('curator_note', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('cover_image', models.URLField(blank=True, max_length=500)),
                ('ambient_video_url', models.URLField(blank=True, max_length=500)),
                ('is_featured', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Collection',
                'verbose_name_plural': 'Collections',
                'ordering': ['-is_featured', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ConsultationBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.CharField(blank=True, max_length=30, unique=True)),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('city_lounge', models.CharField(max_length=100)),
                ('preferred_date', models.DateField()),
                ('preferred_time', models.CharField(max_length=100)),
                ('jewellery_interest', models.CharField(default='Celestial High Jewellery', max_length=120)),
                ('estimated_budget', models.CharField(blank=True, max_length=80)),
                ('hospitality_preference', models.CharField(default='Vintage Champagne & Caviar', max_length=150)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'In Concierge Review'), ('confirmed', 'Confirmed & Reserved'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Consultation Booking',
                'verbose_name_plural': 'Consultation Bookings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FlagshipLounge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=80)),
                ('lounge_name', models.CharField(max_length=150)),
                ('address', models.TextField()),
                ('phone', models.CharField(default='+91 22 8920 4400', max_length=40)),
                ('email', models.EmailField(default='concierge@aetherjewels.com', max_length=254)),
                ('hours', models.CharField(default='Private Appointment Only • 11:00 AM – 8:00 PM IST', max_length=120)),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Flagship Lounge',
                'verbose_name_plural': 'Flagship Lounges',
                'ordering': ['display_order', 'city'],
            },
        ),
        migrations.CreateModel(
            name='JournalArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('category', models.CharField(default='Haute Joaillerie Lore', max_length=80)),
                ('author', models.CharField(default='Madame Vivienne Varma, Master Gemologist', max_length=100)),
                ('read_time', models.CharField(default='5 min read', max_length=30)),
                ('snippet', models.TextField()),
                ('content', models.TextField()),
                ('cover_image', models.URLField(max_length=500)),
                ('published_date', models.DateField()),
                ('is_featured', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Journal Article',
                'verbose_name_plural': 'Journal Articles',
                'ordering': ['-published_date'],
            },
        ),
        migrations.CreateModel(
            name='PressQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication', models.CharField(max_length=100)),
                ('quote', models.TextField()),
                ('author_title', models.CharField(default='Haute Joaillerie Critic', max_length=120)),
                ('badge_text', models.CharField(blank=True, default='Vogue Luxury Honors', max_length=80)),
                ('year', models.CharField(default='2025', max_length=10)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Press Quote',
                'verbose_name_plural': 'Press Quotes',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('price_inr', models.DecimalField(decimal_places=2, help_text='Price in Indian Rupees (INR)', max_digits=12)),
                ('is_price_on_request', models.BooleanField(default=False)),
                ('carat_weight', models.DecimalField(decimal_places=2, default=2.5, max_digits=6)),
                ('metal_type', models.CharField(choices=[('18k_champagne_gold', '18k Celestial Champagne Gold'), ('18k_rose_gold', '18k Starlight Rose Gold'), ('950_platinum', '950 Sovereign Platinum'), ('18k_black_rhodium', '18k Midnight Black Rhodium'), ('18k_dual_gold', '18k Dual Champagne & Platinum')], default='18k_champagne_gold', max_length=60)),
                ('metal_description', models.CharField(default='18k Celestial Champagne Gold (750 Purity)', max_length=150)),
                ('primary_gemstone', models.CharField(default='Golconda Type IIa Diamond', max_length=150)),
                ('gemstone_origin', models.CharField(default='Historic Golconda, India', max_length=120)),
                ('clarity_cut', models.CharField(default='Flawless / D Color / Celestial Brilliant', max_length=150)),
                ('dimensions', models.CharField(blank=True, default='Masterpiece Proportions', max_length=150)),
                ('certification', models.CharField(default='GIA Diamond Dossier & BIS 916 Hallmark', max_length=200)),
                ('description', models.TextField()),
                ('craftsmanship_story', models.TextField(blank=True)),
                ('image_primary', models.URLField(max_length=500)),
                ('image_secondary', models.URLField(blank=True, max_length=500)),
                ('image_detail', models.URLField(blank=True, max_length=500)),
                ('image_editorial', models.URLField(blank=True, max_length=500)),
                ('is_featured', models.BooleanField(default=True)),
                ('is_masterpiece', models.BooleanField(default=False, help_text='Featured in the Pinned Horizontal Scroll Showcase')),
                ('in_stock', models.BooleanField(default=True)),
                ('stock_count', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='atelier.category')),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='atelier.collection')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-is_masterpiece', '-is_featured', '-created_at'],
            },
        ),
    ]
